name: CI
on:
  push:
    branches:
      - main
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run unit tests

        run: |
          # export DISPLAY=:99
          # sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
          xvfb-run code
          npm run test
