name: CI
on:
  push:
    branches:
      - main
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - run: node --version
      - name: Run unit tests

        run: |
          export LIBGL_ALWAYS_INDIRECT=1
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
          sudo service dbus start
          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          # sudo mkdir $XDG_RUNTIME_DIR
          sudo chmod 700 $XDG_RUNTIME_DIR
          sudo chown $(id -un):$(id -gn) $XDG_RUNTIME_DIR
          export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus
          dbus-daemon --session --address=$DBUS_SESSION_BUS_ADDRESS --nofork --nopidfile --syslog-only &
          npm run test
